// comanager-logic §4: task/food-safety due_date values represent a Riyadh
// (UTC+3, no DST) calendar day, generated by
// supabase/functions/generate-daily-slots using new Date(now + 3h)
// truncated to its UTC calendar date. Every client-side "today"/"N days
// ago" computation must use this exact same math — plain
// `new Date().toISOString().slice(0, 10)` is UTC's calendar day, which
// disagrees with Riyadh's for the ~3 hours daily (UTC 21:00-23:59, after
// Riyadh's day has already rolled over but UTC's hasn't). During that
// window, comparing raw-UTC "today" against Riyadh-dated due_date rows
// silently misses the current day's already-generated slots. Audit
// finding, 2026-07-30 — found by reading generate-daily-slots/index.ts
// alongside every page independently computing "today" and noticing they
// didn't share this logic anywhere.
const RIYADH_OFFSET_MS = 3 * 60 * 60 * 1000;

export function riyadhDateString(date: Date = new Date()): string {
  return new Date(date.getTime() + RIYADH_OFFSET_MS).toISOString().slice(0, 10);
}

export function riyadhDaysAgoString(days: number, from: Date = new Date()): string {
  return riyadhDateString(new Date(from.getTime() - days * 24 * 60 * 60 * 1000));
}

// due_date columns are plain "YYYY-MM-DD" strings with no time/zone
// attached. `new Date(dateOnlyString)` parses as UTC midnight, but any
// *local-time* getter called on the result (getDay(), getDate(), ...) is
// then evaluated in the viewer's own browser timezone — silently shifting
// the calendar day by one for any browser west of UTC. A due_date's
// identity (which day of the week it falls on) must never depend on where
// the owner happens to be sitting; always parse and read it in UTC.
export function parseDueDate(dueDate: string): Date {
  const [y, m, d] = dueDate.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}
